/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_unibz_enactmobile_EnActMain */

#ifndef _Included_it_unibz_enactmobile_EnActMain
#define _Included_it_unibz_enactmobile_EnActMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_unibz_enactmobile_EnActMain
 * Method:    multiplyMatricesFromFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActMain_multiplyMatricesFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_unibz_enactmobile_EnActMain
 * Method:    filterImage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActMain_filterImage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_unibz_enactmobile_EnActMain
 * Method:    meteorContestBenchmark
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActMain_meteorContestBenchmark
  (JNIEnv *, jobject);

/*
 * Class:     it_unibz_enactmobile_EnActMain
 * Method:    mandelbrotBenchmark
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActMain_mandelbrotBenchmark
  (JNIEnv *, jobject, jint);

/*
 * Class:     it_unibz_enactmobile_EnActMain
 * Method:    spectralNormBenchmark
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActMain_spectralNormBenchmark
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
