/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_unibz_enactmobile_EnActStart */

#ifndef _Included_it_unibz_enactmobile_EnActStart
#define _Included_it_unibz_enactmobile_EnActStart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_unibz_enactmobile_EnActStart
 * Method:    multiplyMatricesFromFile
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActStart_multiplyMatricesFromFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     it_unibz_enactmobile_EnActStart
 * Method:    filterImage
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActStart_filterImage
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     it_unibz_enactmobile_EnActStart
 * Method:    meteorContestBenchmark
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActStart_meteorContestBenchmark
  (JNIEnv *, jobject);

/*
 * Class:     it_unibz_enactmobile_EnActStart
 * Method:    mandelbrotBenchmark
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActStart_mandelbrotBenchmark
  (JNIEnv *, jobject, jint);

/*
 * Class:     it_unibz_enactmobile_EnActStart
 * Method:    spectralNormBenchmark
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_unibz_enactmobile_EnActStart_spectralNormBenchmark
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
